### ISSUE TITLE
Link for allow gulp task doesn't work

### ISSUE THREAD

**Issue by andreabusi** [davidyack/gulp-webresource#1]
Hi,
I'm tring to configure the task, but I'm not able to complete step number 6.
The link seems doesn't work anymore (http://bit.ly/1Vpj6O2).
Could you verify please?

**Comment by davidyack** [comment]
The link still works, but it redirects after consent to https://xrm.tools/gulp-webresource which apparently hasn't been deployed yet - thanks for mentioning

**Comment by davidyack** [comment]
This has now been resolved - it will now land on a landing page after consent
